model_config:
  lxmert:
    bert_model_name: bert-base-uncased
    training_head_type: pretraining
    random_initialize: false
    training_head_type: classification
    num_labels: 3129
    mode: 'lxr'
    l_layers: 9
    x_layers: 5
    r_layers: 5
    visual_feat_dim: 2048
    visual_pos_dim: 4
    obj_id_num: 1600
    attr_id_num: 400
    taskMatched: true
    taskMaskLM: true
    taskObjPredict: true
    taskQA: true
    visualLosses: true
    visual_loss_config: {
         "obj": (obj_id_num, "ce", (-1,), 1 / 0.15),
         "attr": (attr_id_num, "ce", (-1,), 1 / 0.15),
         "feat": (2048, "l2", (-1, 2048), 1 / 0.15),
     }
    