includes:
- ./defaults.yaml

dataset_config:
  vqa2:
    use_images: false
    use_features: true
    features:
      train:
<<<<<<< HEAD
<<<<<<< HEAD
      - coco/defaults/features/trainval2014.lmdb
      - coco/defaults/features/trainval2014.lmdb
=======
      - coco/defaults/features/coco_trainval2014.lmdb
      - coco/defaults/features/coco_trainval2014.lmdb
>>>>>>> Add files via upload
=======
      - coco/defaults/features/trainval2014.lmdb
      - coco/defaults/features/trainval2014.lmdb
>>>>>>> Add files via upload
    annotations:
      train:
      - vqa2/defaults/annotations/imdb_train2014.npy
      - vqa2/defaults/annotations/imdb_val2014.npy
    return_features_info: true
