dataset_config:
  masked_coco:
    data_dir: ${env.data_dir}/datasets
    depth_first: false
    fast_read: false
    use_images: false
    use_features: true
    use_image_feature_masks: false
    return_features_info: true
    max_features: 36
    use_ocr: false
    use_ocr_info: false
    two_sentence: false
    two_sentence_probability: 0
    false_caption: false
    false_caption_probability: 0.5
    features:
      train:
      - coco/defaults/features/coco_trainval2014.lmdb
      val:
      - coco/defaults/features/coco_trainval2014.lmdb
      test:
      - coco/defaults/features/coco_test2015.lmdb
    annotations:
      train:
      - coco/defaults/annotations/imdb_karpathy_train_by_image.npy
      val:
      - coco/defaults/annotations/imdb_karpathy_val_by_image.npy
      test:
      - coco/defaults/annotations/imdb_karpathy_test_by_image.npy
    processors:
      bbox_processor:
        type: bbox
        params:
          max_length: 36
      text_processor:
        type: bert_tokenizer
        params:
          tokenizer_config:
            type: bert-base-uncased
            params:
              do_lower_case: true
          max_seq_length: 20
      attribute_processor:
        type: vocab
        params:
          max_length: 1
          vocab:
            type: random
            vocab_file: vocabs/vocabulary_100k.txt
      name_processor:
        type: vocab
        params:
          max_length: 1
          vocab:
            type: random
            vocab_file: vocabs/vocabulary_100k.txt
      masked_token_processor:
        type: masked_token
        params:
          tokenizer_config:
            type: bert-base-uncased
            params:
              do_lower_case: true
          mask_probability: 0.15
          max_seq_length: 20

model_config:
  lxmert:
    training_head_type: pretraining

optimizer:
  type: adam_w
  params:
    lr: 1e-4
    eps: 1e-8

training:
  seed: 9595
  batch_size: 64
  lr_scheduler: false
  find_unused_parameters: true
  use_warmup: true
  warmup_factor: 0.05
  warmup_iterations: 1000
  max_epochs: 20
  max_updates: null
