dataset_config:
  masked_gqa:
    data_dir: ${env.data_dir}/datasets
    depth_first: false
    fast_read: false
    use_images: false
    use_features: true
    zoo_requirements:
    - coco.defaults
    - gqa.defaults
    features:
      train:
      - visual_genome/detectron_fix_100/fc6/,visual_genome/resnet152/
      val:
      - visual_genome/detectron_fix_100/fc6/,visual_genome/resnet152/
      test:
      - visual_genome/detectron_fix_100/fc6/,visual_genome/resnet152/
    annotations:
      train:
      - gqa/defaults/annotations/imdb_train2014.npy
      val:
      - gqa/defaults/annotations/imdb_val2014.npy
      test:
      - gqa/defaults/annotations/imdb_test2015.npy
    max_features: 100
    use_image_feature_masks: false
    processors:
      masked_token_processor:
        type: masked_token
        params:
          tokenizer_config:
            type: bert-base-uncased
            params:
              do_lower_case: true
          mask_probability: 0.15
          max_seq_length: 128
    return_features_info: false
    # Return OCR information
    use_ocr: false
    # Return spatial information of OCR tokens if present
    use_ocr_info: false
