dataset_config:
  gqa_train_val:
    use_images: false
    use_features: true
    zoo_requirements:
    - coco.defaults
    - gqa.defaults
    - coco.resnet152
    features:
      train:
      - visual_genome/detectron_fix_100/fc6/,visual_genome/resnet152/
      val:
      - visual_genome/detectron_fix_100/fc6/,visual_genome/resnet152/
      test:
      - visual_genome/detectron_fix_100/fc6/,visual_genome/resnet152/
    annotations:
      train:
      - gqa/defaults/annotations/imdb_train2014.npy
      - gqa/defaults/annotations/imdb_val2014.npy
      val:
      - gqa/defaults/annotations/imdb_minival2014.npy
    data_dir: ${env.data_dir}/datasets
    depth_first: false
    fast_read: false
    max_features: 100
    processors:
      text_processor:
        type: vocab
        params:
          max_length: 14
          vocab:
            type: intersected
            embedding_name: glove.6B.300d
            vocab_file: gqa/defaults/extras/vocabs/vocabulary_100k.txt
          preprocessor:
            type: simple_sentence
            params: {}
      answer_processor:
        type: gqa_answer
        params:
          num_answers: 10
          vocab_file: gqa/defaults/extras/vocabs/answers_gqa.txt
          preprocessor:
            type: simple_word
            params: {}
      context_processor:
        type: fasttext
        params:
          download_initially: false
          max_length: 50
          model_file: wiki.en.bin
      ocr_token_processor:
        type: simple_word
        params: {}
      bbox_processor:
        type: bbox
        params:
          max_length: 50
    return_features_info: false
    # Return OCR information
    use_ocr: false
    # Return spatial information of OCR tokens if present
    use_ocr_info: false
